import { Component, OnInit } from '@angular/core';
import { CafeService } from '../../cafe.service';
import { Item } from '../../model/Item.model';
import { Router } from '@angular/router';
import { take } from 'rxjs';
import { Cart } from '../../model/cart.model';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.css'
})
export class MenuComponent implements OnInit {

  getCategoryList: any[] = [];
  category: any= '';
  categoryItems: Array<Item> = [];
  AllItems: Array<Item> = [];
  customerId: any = '';
  successMessage: string = '';  // Message for cart addition success
  showSuccessMessage: boolean = false;  // Control message visibility

  constructor ( 
    private cafeservice:CafeService,
    private router: Router 
  ) { 
    this.cafeservice.isUserLoginPresent();
    this.customerId = this.cafeservice.getUserAuthorization();

    this.cafeservice.getAllItems().subscribe(items => {
      this.AllItems = items;
      this.categoryItems = this.AllItems;
      console.log('Items are selected :', this.AllItems);
    }, (err: any) => {
        console.log("Error");
      });
    
  }
 
  ngOnInit(): void {
    this.getCategoryList = this.cafeservice.getCategoryList();

  } 


 selectCategory(value: number) {
    this.category = value;
    console.log('Selected category:', this.category);

    this.cafeservice.getItemByCategory(this.category).subscribe(items => {
      this.categoryItems = items;
      console.log('Items for selected category:', this.categoryItems);
    }, (err: any) => {
        console.log("Error");
      });
  }


  selectAllItems(){

    this.cafeservice.getAllItems().subscribe(items => {
      this.AllItems = items;
      this.categoryItems = this.AllItems;
      console.log('Items are selected :', this.AllItems);
    }, (err: any) => {
        console.log("Error");
      });
  }

  
  addToCart(item: Item) {
    const cart = {
      orderItemId: 0, // This might be auto-generated by the backend
      quantity: 1, // Default quantity
      price: item.price,
      totalPrice: item.price * 1, // quantity is 1
      customer: { customerId: this.customerId }, // Create customer object with id
      item: item // Associate the selected item
    };

    this.cafeservice.addToCart(cart, item.itemId, this.customerId).subscribe(response => {
      console.log('Item added to cart:', response);

      this.successMessage = `Item "${item.itemName}" added to cart successfully!`;
      this.showSuccessMessage = true;

      // Hide message after 3 seconds
      setTimeout(() => {
        this.showSuccessMessage = false;
      }, 3000);
      
    }, (err: any) => {
      console.log('Error adding to cart:', err);
    });
  }

}


 

